# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('email', models.CharField(max_length=18)),
                ('flag', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('level', models.IntegerField()),
                ('reason', models.CharField(max_length=18)),
                ('date', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
    ]
